version: "3"
services:
  frontend:
    container_name: tabunganku-frontend
    image: willystw/tabunganku-fe
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: always
    networks:
      fe-network:
        ipv4_address: 172.20.10.4
networks:
  fe-network:
    name: tabunganku-network
    external: true